- name: "install docker on debian"   #install docker on ubuntu and create container
  hosts: all
  become: yes
  tasks:
    - name: Update packages    #install docker on ubuntu or debian 
      shell: apt update -y
    - name: Install docker
      shell: apt install docker.io -y
    - name: install software for pip3
      package:
                  name: "python3"
                  state: present
    - name: install software for pip3
      package:
                  name: "python3-pip"
                  state: present
    - name: Install python lib
      pip:
           name: docker-py
    - name: pull docker image
      docker_image:
                  name: httpd
                  source: pull
                  tag: latest
      register: z
    - name: check pull images
      debug: 
                var: z
    - name: creating a volume
      file:
               path: "/home/preet/voll"
               state: directory
    - name: copy file
      copy: 
               src: "index.html"
               dest: "/home/preet/voll"
    - name: launch container
      when: z.failed == false
      docker_container: 
                name: web
                image: httpd
                state: started
                exposed_ports: 80
                ports: "8888:80"
                volumes: /home/preet/voll:/usr/local/apache2/htdocs